### PR TITLE
support es6 module

### PR DESCRIPTION
**Pull request by hacke2**
like this :

``` js
reactNativeStylesheetCss({
    module: 'es6'
})
```

it wiil be create:

```
import {StyleSheet} from 'react-native';
export default StyleSheet.create({
    "container": {
        "flex": 1,
        "justifyContent": "center",
        "alignItems": "center",
        "backgroundColor": "#F5FCFF"
    },
    "welcome": {
        "fontSize": 20,
        "textAlign": "center",
        "marginTop": 10,
        "marginBottom": 10,
        "marginRight": 10,
        "marginLeft": 10
    },
    "instructions": {
        "textAlign": "center",
        "color": "#333333",
        "marginBottom": 5
    }
});
```

### CODE REVIEW

**Comment by hacke2** [comment]
@jjshammas

**Comment by jjshammas** [comment]
Great idea @hacke2. Do you think es6 should be the default and es5 should be opt-in? I was never clear on which route React Native prefers.

**Comment by sylvainbaronnet** [comment]
IMO es6 by default seems more appropriate for RN

**Comment by hacke2** [comment]
es6 must be the default 😆  +1

**Comment by hacke2** [comment]
but now dependent on the module project will complain  If es6 is default

**Pull request merged**
